### ISSUE TITLE
Version 2.5.2 throwing error in OpenJDK Instance

### ISSUE THREAD

**Issue by hcrites54** [OSCELOT/UoY-DSK-Tool#2]
Good afternoon!

The Q1 Technical Preview is running a beta version of Learn 3700.0.0 that includes OpenJDK.  The specific release is 3700.99.0-ci.379+3074826.  At the moment, there is no definitive date or release for the implementation of OpenJDK.

We have installed UofYork DSK version 2.2.0, 2.5.0, and 2.5.2 in this instance and all are throwing the following error message when the System Admin > UoY Data Source Key Tool link is clicked:

> Servlet.init() for servlet [appServlet] threw exception javax.annotation.Resource.lookup()Ljava/lang/String;
> For reference, the Error ID is 1e58b325-ff04-4302-8f14-cc5bbe1a319f.
> Tuesday, June 4, 2019 at 12:46:35 PM Eastern Daylight Time

Unfortunately, I cannot access the logs at the moment since they have deprecated Kibana. I will try to pull them out once they are available in about four hours. 

Thanks!
Heather

**Comment by hcrites54** [comment]
Hello!

This is the full entry in the logs for this error:

> 
> {
> 	"path":"/usr/local/blackboard/logs/bb-services-log.txt"
> 	"@timestamp":"2019-06-04T16:55:24.861Z"
> 	"clientid":"5c6c630989634"
> 	"@version":"1"
> 	"host":"ip-10-147-33-60"
> 	"message":"2019-06-04 12:46:35 -0400 - [WARNING] Servlet.init() for servlet [appServlet] threw exception javax.annotation.Resource.lookup()Ljava/lang/String;<P><span class=\"captionText\">For reference, the Error ID is 1e58b325-ff04-4302-8f14-cc5bbe1a319f.</span> - java.lang.NoSuchMethodError: javax.annotation.Resource.lookup()Ljava/lang/String;\n\tat org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.<init>(CommonAnnotationBeanPostProcessor.java:609)\n\tat org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.lambda$buildResourceMetadata$0(CommonAnnotationBeanPostProcessor.java:373)\n\tat org.springframework.util.ReflectionUtils.doWithLocalFields(ReflectionUtils.java:692)\n\tat org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.buildResourceMetadata(CommonAnnotationBeanPostProcessor.java:355)\n\tat org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.findResourceMetadata(CommonAnnotationBeanPostProcessor.java:339)\n\tat org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:298)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1020)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)\n\tat org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)\n\tat org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)\n\tat org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)\n\tat org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1348)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)\n\tat org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)\n\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n\tat org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:672)\n\tat org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:638)\n\tat org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:686)\n\tat org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:554)\n\tat org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:499)\n\tat org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:172)\n\tat javax.servlet.GenericServlet.init(GenericServlet.java:158)\n\tat jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:282)\n\tat org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:279)\n\tat java.base/java.security.AccessController.doPrivileged(Native Method)\n\tat java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)\n\tat org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:314)\n\tat org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170)\n\tat org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:123)\n\tat org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1132)\n\tat org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)\n\tat org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:773)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)\n\tat org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:539)\n\tat org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)\n\tat org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)\n\tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)\n\tat blackboard.tomcat.valves.LoggingRemoteIpValve.invoke(LoggingRemoteIpValve.java:51)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:834)"
> 	"type":"learn"
> 	"tags":["multiline","learn"]
> }

I have been told they may be targeting August or September for OpenJDK deployment.

Please let me know how I can help.

Thanks!
Heather

**Comment by Kelvin-Hai** [comment]
@hcrites54 

I just downloaded the DVM and will take a look at the issue soon.

**Comment by hcrites54** [comment]
Thanks. Please let me know if I can help.

**Comment by Kelvin-Hai** [comment]
@hcrites54 
This should be fixed in v2.5.3. I've only tested the new release on a DVM (3700.99.0-ci.333+3145f8f).

**Comment by hcrites54** [comment]
Loaded it into Tech Preview. Works perfectly.  Thank you so much for all of your help! We should be good to go for Corretto.

**Comment by Kelvin-Hai** [comment]
Excellent. No problem.
