### ISSUE TITLE
3900.17.0 Breaks Launch

### ISSUE THREAD

**Issue by sstaggs1** [OSCELOT/UoY-DSK-Tool#9]
I began testing the new installation of Blackboard on our test environment this morning. I found that a couple of our B2s weren't launching anymore, and were throwing an error. Since this is a very important B2 to our university as well I tested it too. I get the following as soon as the launch link is clicked:
ServletException including path '/WEB-INF/tiles/layouts/layout_default.jsp'. /WEB-INF/tiles/layouts/layout_default.jsp (line: [30], column: [0]) The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in either web.xml or the jar files deployed with this application

This is with version 2.6.0 installed on Learn Release 3900.17.0-rel.18+4d5e1cf

**Comment by jkelley-blackboard** [comment]
On what type of deployment?  Is this in your AMI, local deployment or your test/staging SaaS deployment?  I cannot replicate the issue on my test/staging deployment.

**Comment by sstaggs1** [comment]
This is on our SaaS Test/Staging deployment
This is presenting in both Chrome 91.0.4472.106 and Firefox 89.0.1
I have also opened a ticket with Blackboard regarding this since it is affecting multiple B2s. But I thought I should report the issue here as well in case the problem isn't with them.

**Comment by jkelley-blackboard** [comment]
if you'd like another set of eyes, feel free to email me the details and I will take a look - jeff.kelley@blackboard.com    (Note that we have announced the long term end of life of Building Blocks, so you might want to take a look at the REST-based option too.  https://github.com/moneil/OSCELOT-DSKTOOL-for-HEROKU)

**Comment by jkelley-blackboard** [comment]
Seems to be a known issue:  Your test/staging should soon be updated to 3900.17.0-rel.24+35b8869 .  https://help.blackboard.com/Learn/Administrator/SaaS/Release_Notes

**Comment by sstaggs1** [comment]
I see that I didn't pay enough attention to the release version on my test environment.
